Changed to conf template folder
To fix issue with
Error: TEMPLATECONF value xx must point to meta-some-layer/conf/xxx

Apperantly the old way does not work anymore. Reason commit

scripts/oe-setup-builddir: add a check that TEMPLATECONF is valid